In [2]:
from keras.models import load_model
from tensorflow.keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt
import os
import joblib
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from pickle import load

In [3]:
model = load_model('D:/AI_Alignment/cnn_2d.keras',compile=False)
model.compile(optimizer=Adam(),loss='mae',metrics=['mae'])

In [4]:
scaler = load(open('D:/AI_Alignment/MinMaxScaler.pkl','rb'))

UnpicklingError: invalid load key, '\x03'.

In [41]:
wavefront_maps = []



for i in range(1):
    folder_path = 'C:/Users/galaxy/Desktop/부엉이'
    wfm_data = []

    for j in range(1, 6):
        file_path = os.path.join(folder_path, f'wfm_{j}.txt')
        wfm_temp = []
        with open(file_path, 'r', encoding='utf-16') as f:
            lines = f.readlines()[16:]
            data = np.array([list(map(float, line.split())) for line in lines])
            wfm_temp.append(data)
        wfm_temp = np.array(wfm_temp).reshape(1,-1)
        wfm_scaled = scaler.transform(wfm_temp)
        wfm_temp = wfm_temp.reshape(64,64)
        wfm_data.append(wfm_temp)
                
    wfm_data = np.array(wfm_data).reshape(5, 64, 64, 1)
    wavefront_maps.append(wfm_data) 

wfm = np.array(wavefront_maps)

In [50]:
prediction = model.predict(wfm)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([[ 108.19303  ,   -4.0836077,    1.5014119,    8.62114  ,
         -82.42914  , -109.39208  ]], dtype=float32)

In [54]:
np.min(wfm)

-14.49727

array([-0.2213474])

In [28]:
wavefront_maps = []


for i in range(1):
    folder_path = 'D:/AI_Alignment/algorithm_data/data10650'
    wfm_data = []

    for j in range(1, 6):
        file_path = os.path.join(folder_path, f'wfm_{j}.txt')
        with open(file_path, 'r', encoding='utf-16') as f:
            lines = f.readlines()
            data = np.array([list(map(float, line.split())) for line in lines])
            wfm_data.append(data)
                
    wfm_data = np.array(wfm_data).reshape(5, 64, 64, 1)
    wavefront_maps.append(wfm_data) 

wfm = np.array(wavefront_maps)

In [30]:
wfm = wfm.reshape(1,5,64,64,1)

In [34]:
X_reshaped = wfm.reshape(-1, 64*64)
X_scaled = scaler.fit_transform(X_reshaped).reshape(-1, 5, 64, 64, 1)

NameError: name 'scaler' is not defined

In [31]:
prediction = model.predict(wfm)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[ 27.946653 ,  73.57182  , -10.207854 , -50.230877 , -40.402225 ,
         -2.3992648]], dtype=float32)